name: dart_code_metrics_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 4.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_code_metrics:
    git:
      url: https://dev.azure.com/hci-iap/koyal/_git/koyal-analyzer
      ref: main